### ISSUE TITLE
Installation using `nix-env` fails because the tarball is not a git repo

### ISSUE THREAD

**Issue by pricebenjamin** [arximboldi/immer#100]
According to the README:

https://github.com/arximboldi/immer/blob/559ab37543a7076f9cfe9002720b0d5ad6ffc12a/README.rst#L169-L172

However, running this command results in the following error:

```
installing 'immer-git'
fatal: '/nix/store/ilk9xjlhjrma9zc92zi56yf3malnsyvv-master.tar.gz' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error: program 'git' failed with exit code 128
(use '--show-trace' to show detailed location information)
```

Indeed, when you fetch tarballs from `https://github.com/<repo>/archive` and unpack them, the resulting folder is not a git repository.

One solution, if you wish to install with Nix, is to clone the repo and install via the `default.nix` expression.

```bash
$ git clone https://github.com/arximboldi/immer
$ cd immer
$ nix-env -if ./default.nix
```

**Comment by arximboldi** [comment]
Oh yeah... I did a change to make it easier to install `immer` when you have already cloned it, but that of course fucked this other use-case. I shall look for a workaround or just change the docs.

**Comment by esp1** [comment]
I ran into this problem today when trying to install immer via nix. If the docs can at least be updated it would make for a much better initial experience with immer!

**Comment by esp1** [comment]
I am also not able to install nix correctly by cloning the repo and running `nix-env -if ./default.nix`. I get this error:
```
% nix-env -if ./default.nix
installing 'immer-git'
this derivation will be built:
  /nix/store/0w63gn2r8967758kw79afw9w6npf84wz-immer-git.drv
building '/nix/store/0w63gn2r8967758kw79afw9w6npf84wz-immer-git.drv'...
unpacking sources
unpacking source archive /nix/store/jmmb5lpfci90l3s87ynvp0r67nr8ikl4-source
source root is source
patching sources
configuring
fixing cmake files...
mkdir: cannot create directory 'build': File exists
error: builder for '/nix/store/0w63gn2r8967758kw79afw9w6npf84wz-immer-git.drv' failed with exit code 1;
       last 7 log lines:
       > unpacking sources
       > unpacking source archive /nix/store/jmmb5lpfci90l3s87ynvp0r67nr8ikl4-source
       > source root is source
       > patching sources
       > configuring
       > fixing cmake files...
       > mkdir: cannot create directory 'build': File exists
       For full logs, run 'nix log /nix/store/0w63gn2r8967758kw79afw9w6npf84wz-immer-git.drv'.
```
The log shows:
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/jmmb5lpfci90l3s87ynvp0r67nr8ikl4-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
mkdir: cannot create directory 'build': File exists
```
I don't know what build file it is complaining about; I don't see one in the cloned immer project.

**Comment by arximboldi** [comment]
@esp1 sadly the `BUILD` file can not be renamed, because it is part of the Bazel support. I am gonna try fix both these issues now...

**Comment by arximboldi** [comment]
Fixed now, sorry for the inconveniences!
