### ISSUE TITLE
Integrating with OSS-Fuzz

### ISSUE THREAD

**Issue by Google-Autofuzz** [arximboldi/immer#102]
Greetings immer developers and contributors,

We’re reaching out because your project is an important part of the open source ecosystem, and we’d like to invite you to integrate with our [fuzzing](https://www.owasp.org/index.php/Fuzzing) service, [OSS-Fuzz]( https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html ). OSS-Fuzz is a free fuzzing infrastructure you can use to identify security vulnerabilities and stability bugs in your project. OSS-Fuzz will:
- Continuously run at scale all the fuzzers you write.
- Alert you when it finds issues.
- Automatically close issues after they’ve been fixed by a commit.

Many widely used [open source projects]( https://github.com/google/oss-fuzz/tree/master/projects ) like OpenSSL, FFmpeg, LibreOffice, and ImageMagick are fuzzing via OSS-Fuzz, which helps them find and remediate [critical issues]( https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+Type%3ABug%2CBug-Security+-component%3AInfra+ ). 

Even though typical integrations can be done in < 100 LoC, we have a [reward program]( https://www.google.com/about/appsecurity/patch-rewards/ ) in place which aims to recognize folks who are not just contributing to open source, but are also working hard to make it more secure.

We want to stress that anyone who meets the eligibility criteria and integrates a project with OSS-Fuzz is eligible for a reward.

If you're not interested in integrating with OSS-Fuzz, it would be helpful for us to understand why—lack of interest, lack of time, or something else—so we can better support projects like yours in the future.

If we’ve missed your question in our [FAQ]( https://google.github.io/oss-fuzz/faq/ ), feel free to reply or reach out to us at oss-fuzz-outreach@googlegroups.com.

Thanks!

Tommy
OSS-Fuzz Team

**Comment by arximboldi** [comment]
This is pretty cool :)

I indeed already wrote some fuzzing before that I run locally in some hardening rounds in the past: https://github.com/arximboldi/immer/tree/master/extra/fuzzer

It would of course be great to run them continously using Google infra!

I am pretty busy at the moment but I am looking forward to making the integration eventually. I hope maybe some sponsor can help with this.

**Comment by arximboldi** [comment]
Checked the reward program, I think that counts as "sponsor" :smile: I think we can indeed make some nice integration there. Working on it, will keep you posted.

**Comment by Google-Autofuzz** [comment]
> Checked the reward program, I think that counts as "sponsor"  I think we can indeed make some nice integration there. Working on it, will keep you posted.

That would be great for you.

**Comment by Google-Autofuzz** [comment]
@arximboldi How's the integration going? We can also help by starting the OSS-Fuzz integration process for you if lack of time. We just need a google email from you to send bugs to you when libfuzzer finds any.

**Comment by arximboldi** [comment]
We are working on it, thanks! I'll get back as we have something to show.

**Comment by arximboldi** [comment]
Sorry for the long silence. Had to set it assied and move to other things. Actively working on it now, will bring results this week. Thank you for your patience!

**Comment by arximboldi** [comment]
PR ready: https://github.com/google/oss-fuzz/pull/4129

**Comment by arximboldi** [comment]
An initial integration has been merged!
