### ISSUE TITLE
Website: free_list_heap_policy claims to not be default, despite being default

### ISSUE THREAD

**Issue by nyanpasu64** [arximboldi/immer#106]
[The website claims](https://sinusoid.es/immer/memory.html#structimmer_1_1free__list__heap__policy) `default_heap_policy` "might become the default in the future."

But [default_heap_policy](https://sinusoid.es/immer/memory.html#memory__policy_8hpp_1ac2170ddaa40fee0db357f16911498ac7) claims `default_heap_policy = free_list_heap_policy<cpp_heap>` and already uses `free_list_heap_policy` as default.

Does the website need to be updated?

**Comment by arximboldi** [comment]
Fixed in 36d1000deba7ad06f9976bc0bbe94d589690dc8a
Thanks!
