### ISSUE TITLE
Add support for VS 2017

### ISSUE THREAD

**Issue by acki-m** [arximboldi/immer#11]
I tried compilation of the latest master with VS2017,
but I get a compile error:
```
inline constexpr auto clz_(unsigned int x) { return __builtin_clz(x); }
immer/detail/util.hpp(82): error C3861: '__builtin_clz': identifier not found
```
Can you please add support for VS 2017?

**Comment by arximboldi** [comment]
Hi @acki-m!

Thanks a lot for reporting the issue. I agree that this is an important feature. In it somewhere in the roadmap, but at the moment I must admit there are other features above that.

If this is important for a commercial project you are working on, I suggest joining the sponsorship program. Alternatively we could agree on some consulting time for your project to help finance this work. In this way I could guarantee to develop it in a timeline tailored to your needs, and I could also do extra work to make sure the library works for you. Send me an to juanpe@sinusoid.al if you are interested!

PS. I see you are in Berlin... I live there too, so we could meet in offline space to discuss this further too. I also attend the C++ meetup often.

**Comment by acki-m** [comment]
Hi Juan,
We actually meet each other, I attended the C++ meet up where you presented your library. Which was actually one of the best presentation I've heard :thumbsup:. And that lead me to your github page.

At the moment I just want to evaluate the library for myself and cannot sponsor anything.
What I can sponsor you is setting up AppVeyor-CI myself to test your library under windows.
However, I can only recommend you to invest supporting the MSVC-Toolchain. There are a lot of potential customers.

**Comment by arximboldi** [comment]
Thanks a lot for the kind words 😊 

I'll keep the issue open and ping you back when I get started with the MSVC work so you can test it.

**Comment by tnovotny** [comment]
i can get this to compile with VS2017 using /std:c++17

    #include "immer/flex_vector.hpp"
    
    int main() {
        immer::flex_vector<int> is;
    }

by patching the log2 calculation (line 87)

    #if 0

    template <typename T>
    inline constexpr auto clz_(T) -> not_supported_t { IMMER_UNREACHABLE; return {}; }
    inline constexpr auto clz_(unsigned int x) { return __builtin_clz(x); }
    inline constexpr auto clz_(unsigned long x) { return __builtin_clzl(x); }
    inline constexpr auto clz_(unsigned long long x) { return __builtin_clzll(x); }

    template <typename T>
    inline constexpr T log2_aux(T x, T r = 0)
    {
        return x <= 1 ? r : log2(x >> 1, r + 1);
    }

    template <typename T>
    inline constexpr auto log2(T x)
        -> std::enable_if_t<!std::is_same<decltype(clz_(x)), not_supported_t>{}, T>
    {
        return x == 0 ? 0 : sizeof(std::size_t) * 8 - 1 - clz_(x);
    }

    template <typename T>
    inline constexpr auto log2(T x)
        -> std::enable_if_t<std::is_same<decltype(clz_(x)), not_supported_t>{}, T>
    {
        return log2_aux(x);
    }

    #else

    template <typename T>
    inline constexpr T log2_aux( T x, T r = 0 )
    {
       return x <= 1 ? r : log2_aux( x >> 1, r + 1 );
    }


    template <typename T>
    inline constexpr auto log2( T x ) -> T
    {
       return log2_aux( x );
    }

    #endif

Please not the patch in `log2_aux` to call itself and not `log`

**Comment by tnovotny** [comment]
Nevermind. I just noticed the pull request.

**Comment by arximboldi** [comment]
Thanks @tnovotny! I still haven't had found the time try out this PR. Will get to it as soon as possible. If some other Windows expert wants to try it out, that's great. Ideally, the unit-tests included in the library should pass. Eventually we should add AppVeyor support to ensure all platforms work great.

**Comment by tnovotny** [comment]
Neither did I. I looked at parts of the other PR and your comments on it, and decided to go for less (only msvc not clang on windows). I wanted minimal changes. I have not  run the unit tests. I also don't know whether or not you want your code sprinkled with warning disabling `#pragmas` so I have not bothered with the warnings. I will add a PR and you can choose which way you wanna go.

**Comment by vincent-hui** [comment]
Hi, did anyone tried Clang in Visual Studio 2017?? https://blogs.msdn.microsoft.com/vcblog/2017/03/07/use-any-c-compiler-with-visual-studio/

**Comment by martinfinke** [comment]
> did anyone tried Clang in Visual Studio 2017??

If you need binary compatibility, then that would be Clang/C2. That uses an old clang version, and isn't being updated anymore.

I just came across the same issues with VS2017. I don't have a fast-and-easy solution for this, but I want to leave some feedback. I really respect the work that has gone into the library, thank you. But I've decided to drop it from my project. I was using it only in one place in my code, so in my case, replacing that bit by my own code is more reasonable than sponsoring to get Visual Studio support. Still, good luck with this project. I'm still convinced that it's probably an excellent choice for other projects and scenarios. 👍

**Comment by vincent-hui** [comment]
@martinfinke did you try Visual Studio 2017 15.7?

**Comment by arximboldi** [comment]
Thanks @martinfinke for the feedback. I understand that Vistual Support is critical for many projects and I really hope that we can make this happen sooner than later. Cheers!

**Comment by martinfinke** [comment]
@vincent-hui Yes, VS2017 15.7.1 Community

**Comment by vincent-hui** [comment]
@martinfinke Did you try building immer with and without Clang/C2?
Microsoft claimed The MSVC compiler toolset in Visual Studio version 15.7 conforms with the C++ Standard.
https://blogs.msdn.microsoft.com/vcblog/2018/04/26/announcing-msvc-conforms-to-the-c-standard/

**Comment by martinfinke** [comment]
@vincent-hui The code that prevents immer from compiling, like `__builtin_clz `, is not part of the C++ standard.

**Comment by totalgee** [comment]
This issue could probably be closed...the MSVC issue mentioned (compile error due to `__builtin_clz`) was fixed by @arximboldi in PR #60 (back in October 2018). I had no problems building a project that uses immer with VS2017 (and MSVC compiler), using the latest immer release ([0.6.2](https://github.com/arximboldi/immer/releases/tag/v0.6.2)).

Note that there are still plenty of compile warnings with default build settings on VS2017 when building a 64-bit project, because `detail::rbts::count_t` is defined as 32-bit (`std::uint32_t`) in bits.hpp. On 64-bit MSVC builds you get a warning when calling many internal methods (such as `push_tail_mut()` or `ensure_mutable_tail()`, in rrbtree.hpp) that expect a 32-bit `count_t` argument but are passed 64-bit arguments (of `detail::rbts::size_t` aka `std::size_t`). These warnings are probably harmless, but annoying.

For the record, the warnings are of these two types:

```
immer\detail\rbts\rrbtree.hpp(956): warning C4267: 'argument': conversion from 'size_t' to 'immer::detail::rbts::count_t', possible loss of data

immer\detail\rbts\position.hpp(1066): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)
```

Both types are quite easily fixed (using `static_cast`), but I'm not absolutely sure whether it's correct and safe to do so in all cases, or whether the underlying types should be reconsidered for 64-bit builds.

**Comment by arximboldi** [comment]
Hi @totalgee.
1. The first warning is actually ignorable, the code is correct because `tail_size == branches<BL>`, which is a small and in the `count_t` domain. Actually probably the problem goes away by replacing `tail_size` by `braches<BL>` in that branch.
2. The second warning actually indicates a potential problem, we shall use `size_t{1} << shift_t` instead of `1 << shift_t`. (Good catch by the compiler there, impressed!)

**Comment by arximboldi** [comment]
I just closed the issue because as @totalgee pointed out, there is already MSVC 2017 support.

*However*! I feel unconfortable that there is no CI pipeline ensuring the MSVC support remains working. I just opened an issue to keep track of this #92

**Comment by acki-m** [comment]
Seriously Juan?
Open since almost 1 year: https://github.com/arximboldi/immer/pull/68
You just need to create a appveyor account.

**Comment by jimbo1qaz** [comment]
https://github.com/arximboldi/immer/blob/0c174600d9532254d184098d6c521d8c17f44ae1/immer/detail/rbts/position.hpp#L1066

It seems that master still uses `1 << shift_t` instead of `size_t{1} << shift_t`. Will this be fixed?

**Comment by arximboldi** [comment]
@jimbo1qaz thanks for the report. That can potentially lead to issues in containers with more than 2^32 elements (on amd64 machines at least). It should be fixed for sure!
