### ISSUE TITLE
How to determine if two containers (flex_vector) share the same identity?

### ISSUE THREAD

**Issue by nyanpasu64** [arximboldi/immer#114]
I'm writing an audio engine which needs to recompute note timings each time the list of events changes.

It seems like flex_vector's memory layout is a rrbtree, which contains a few pointers/integers, and should be comparable for "identity equality" (not content equality).

Is there a constant-time way to check if a `immer::flex_vector` shares the same identity as another one (they're copies of each other or another object)? I'm using this in order to invalidate/recompute a program cache.
- == vec.begin()?
- `#define private public` and == `vec.impl_.root`?

What about other container types (specifically `immer::array`)?

**Comment by arximboldi** [comment]
You could do:
```
a.impl().root == b.impl().root && a.impl().tail == b.impl().tail;
```
However `operator==` already on subtrees that share equal identity. This means that in vectors with structural sharing, `operator==` time is proportional to the amount of change or `O(|diff(a, b)|)`. I think it's probably enough for your use-case, it is definitely enough for my use-cases in similar situations with audio engines.
