### ISSUE TITLE
Pattern for building other data structure on top of immer

### ISSUE THREAD

**Issue by zeyangl** [arximboldi/immer#117]
Hi, I'm trying to write a immutable 2d grid class in terms of immer. I wonder what's a good pattern for implementing data structures on top of immer. I have something like this:

![image](https://user-images.githubusercontent.com/1244606/71247261-572c4c00-2353-11ea-876f-61178a709f30.png)

Specifically I'm curious if that is the "correct" way to do the Set function. To maintain immutability, I ended up specifically copying *this first, then do the immutable set on array. It looks a bit redundant. Just want to get an expert's opinion on this. Thanks

**Comment by arximboldi** [comment]
Hey!

Cool that you are using immer for that!

Some notes:

1. You can replace `Grid ret = *this;` for
```cpp
auto ret = *this;
```
2. The `std::move(ret)` at the end of the function is redundant and pesimizing, use `ret` instead.
3. For performance, you may want to add a separate overload `Grid&& Set(Vec2i p, const T& v) &&` for a moved from value,
4. For performance, you may want to change `const T& v` for `T v` and do `std::move(v)` in the body.
5. To avoid having two overloads for Set (one for `const&` and another for `&&`) you may wanna turn that into a free function.

**Comment by arximboldi** [comment]
I hope this helps!

Cheers!

**Comment by zeyangl** [comment]
Thanks for the reply. The context here is I'm trying to build a tile map editor for our game. Immer looks like a good option to save a lot of work on state mangement and  the undos. Indeed that std::move(ret) is redundant. I agree with all your points except maybe 4. Could you elaborate in what situation is that better for performance?

**Comment by arximboldi** [comment]
If you do `const T& v`, then the value will always be copied into the container. If you do `T v` and then move, the value will be copied only if you pass an l-value to the `Set` function, otherwise it will be a chain of moves and there will be no superfluous copy.

**Comment by zeyangl** [comment]
Yeah I now see how this maps to the immer doc's section on const. Thanks
