### ISSUE TITLE
Fix warning in Xcode 11

### ISSUE THREAD

**Issue by zeyangl** [arximboldi/immer#118]
immer now generates the following warnings in Xcode 11(and similar in Visual Studio 2019) 
![image](https://user-images.githubusercontent.com/1244606/71654618-aae45f80-2d6d-11ea-816f-95fe587cbbb0.png)
It would be nice if these could be fixed.

**Comment by arximboldi** [comment]
Thanks, I will look into fixing them. Which `clang` version and warning flags do you have enabled?

**Comment by arximboldi** [comment]
(In any case, the warnings are innocuous, the conversions are correct since the values are whithin range.)

**Comment by zeyangl** [comment]
Yes they are innocuous indeed, just a bit annoying. If the fix is trivial and harmless then probably better to have it than not. I believe the -Wconversion is enabled by default in Xcode's clang(likely 8.0) but not so with the nix-shell env.

**Comment by arximboldi** [comment]
Yes. Sadly the fix suggested is not harmless since it changes the sizes of things. I will look into another fix. Thanks anyways for your efforts!

**Comment by arximboldi** [comment]
Closing this for now. You should anyway include external dependencies with `-isystem` to avoid such false positives.
