### ISSUE TITLE
Missing immer::set<T>::find( ) method.

### ISSUE THREAD

**Issue by bredelings** [arximboldi/immer#121]
Hi, currently it seems that immer::set provides count( ) but not find( ), while immer::map provides both.  Would it be possible to add an immer::set<T>::find( ) function?

I have a data type that has some fields that are used as annotations.  They affect neither equality (==) or the hash function.  I am interested in looking up an element, and finding the (possibly different) version of that element in the set, and check to see if their notes are equal.  This is possible with std::set, and it is possible with immer, but only if you walk through the entire set.

One might argue that this is bad design, but it DOES make transitioning from std::set< > more difficult.

If you are opposed to this, maybe a note in the header could be added that is similar in length to the note that explains why map::find( ) does not return an iterator?  (BTW, I like the logic there for returning a pointer, given limitations on std::optional).

**Comment by arximboldi** [comment]
Yes, the logic was that `count()` is enough if you consider it a mathematical set. The case of adding annotations o better covered by `map<>`. However, I understand the use-case and it should indeed be an easy to add feature, I accept the feature request :+1: :slightly_smiling_face:
