### ISSUE TITLE
Add COW element access on transients?

### ISSUE THREAD

**Issue by arximboldi** [arximboldi/immer#122]
This would allow to do std::sort directly saving some copies. Not sure whether it is a good idea though. There are some drawbacks.

**Comment by kevin--** [comment]
attempting to do `std::sort` on a `immer::vector` -- is this just out of the question right now, or must you copy your contents to an STL container to perform `std::sort`?

**Comment by arximboldi** [comment]
Yes, right now one has to copy the elements into a `std::vector`. I've considered adding COW element access, but I actually doubt it will be faster in this case. Since every element is touched, more than once actually, I think the relatively high constant on random access on `immer::vector` is higher than copying it all into a `std::vector` and back (which when done properly should be pretty fast!).

**Comment by arximboldi** [comment]
Which I realize, the fastest way to convert an `immer::vector` to `std::vector` is maybe not obvious. ~~Actually, I'm not sure which of these two versions is actually faster:~~
```c++
template <typename T>
std::vector<T> `to_std(const immer::vector<T>& v)
{
    auto r = std::vector<T>{};
    r.reserve(v.size());
    immer::copy(v, std::back_inserter(v));
    return r;
}

std::vector<int> to_std(const immer::vector<int>& v)
{
    auto r = std::vector<int>{};
    r.reserve(v.size());
    immer::for_each_chunk(v, [&](auto b, auto e) {
        r.insert(r.end(), b, e);
    });
    return r;
}
```
I'm sure now: https://godbolt.org/z/d5n1Wj8MK

**Comment by arximboldi** [comment]
This makes me think, maybe this is such a common thing to do that a family of `to_std` and `from_std` functions would make sense in Immer!

**Comment by kevin--** [comment]
yes that makes a lot of sense to provide the std conversion routines. I have written the `from_std` equivalent for interop with a serialization library... For now I am maintaining a sorted collection in `flex_vector` as described in https://github.com/arximboldi/immer/issues/105 using `std::lower_bound`

Thanks also for the tip on `BENCHMARK` in godbolt!

**Comment by tusooa** [comment]
> ```c++
> template <typename T>
> std::vector<T> to_std(const immer::vector<T>& v)
> {
>     auto r = std::vector<T>{};
>     r.reserve(v.size());
>     immer::copy(v, std::back_inserter(v));
>     return r;
> }
> ```
> I'm sure now: https://godbolt.org/z/d5n1Wj8MK

it should be `immer::copy(v, std::back_inserter(r));`

the resulting test result is not *that* ridiculous, though 1 is still slower.

```
-------------------------------------------------------------
Benchmark                   Time             CPU   Iterations
-------------------------------------------------------------
benchmark_to_std_1    2517592 ns      1367175 ns          454
benchmark_to_std_2    1232508 ns       527364 ns         1259
```

**Comment by arximboldi** [comment]
You are right, sorry!

Corrected godbolt: https://godbolt.org/z/h3cvr7qen
