### ISSUE TITLE
Heap corruption in arrays/node.hpp

### ISSUE THREAD

**Issue by kuukunen** [arximboldi/immer#127]
(Visual Studio 2019 16.5.3)

Had some heap corruption issues in make_n. With small arrays like empty array<char>, it seems sizeof_n can return sizes smaller than sizeof(node_t), and then the node_t constructor breaks the heap. Added a quick fix by just doing max(sizeof_n(n), sizeof(node_t)) but not sure if that's optimal, as I'm not entirely sure what sizeof_n is trying to accomplish.

**Comment by arximboldi** [comment]
Can you please provide an example that reproduces this? I'd be then happy to provide a fix myself.

**Comment by kuukunen** [comment]
Sure, it's pretty simple:
```cpp
#include "immer/array.hpp"

int main()
{
	immer::array<char> arr;
	return 0;
}
```
In arrays/node.hpp, in make_n, sizeof_n(n), and thus the allocation, ends up being 5 even though sizeof(node_t) is 8.

In Debug mode, (in MSVC) this will trigger an error indicating heap corruption. Depending on the platform, this might or might not be an issue, since presumably most allocators would just ignore the couple of extra bytes due to alignment, but either way, it should probably be fixed.

**Comment by arximboldi** [comment]
`AddressSanitizer` and `UBSanitizer` do not complain. I'm not sure exactly what MSVC is complaining about, maybe I can investigate further but I do not have a Windows machine at the moment.

You can try changing:
```
    constexpr static std::size_t sizeof_n(size_t count)
    {
        return immer_offsetof(impl_t, d.buffer)
            + sizeof(T) * (count == 0 ? 1 : count);
    }
```
To:
```
    constexpr static std::size_t sizeof_n(size_t count)
    {
        return std::max(
              immer_offsetof(impl_t, d.buffer) + sizeof(T) * count,
              sizeof(node));
    }
```
If that fixes the issue feel free to make a PR.

**Comment by kuukunen** [comment]
Well the exact complaint comes in a form of a messagebox with "HEAP CORRUPTION DETECTED: after Normal block (#75) at 0x00FE50E0.
CRT detected that the application wrote to memory after end of heap buffer."
Basically with char, immer_offsetof(impl_t, d.buffer) == 4 and sizeof(char) == 1, so the allocation ends ends up being 4+1 = 5 bytes, and because sizeof(node_t) == 8, it tries to construct in allocation that is not big enough.

I didn't really look into what combine_standard_layout_t is supposed to do though.

And yes, that is actually the fix we implemented, but there was some other problem that came after it... it went away with rebuild, so I'll monitor the situation a bit before sending a PR.
