### ISSUE TITLE
A typo in the dockerfile

### ISSUE THREAD

**Issue by wangluochao902** [arximboldi/immer#133]
https://github.com/arximboldi/immer/blob/b34af760d64a5948a87c0b2cde90b1aaab5aad67/tools/docker/icfp17/Dockerfile#L23
Hi, we are developing a tool to detect typos/bugs in dockerfiles automatically. Our tool finds a potential typo above. Is it a typo? You have double dashes at the end of the line. Our tool is currently available here https://wangluochao902.github.io/clcheck/

**Comment by arximboldi** [comment]
This is not a typo, it allows using `\` at the end of the last entry in the list before.
