### ISSUE TITLE
emplace, emplace_back, emplace_front

### ISSUE THREAD

**Issue by elfprince13** [arximboldi/immer#136]
It would be great if vector and flex_vector supported `emplace` counterparts for `set`, `push_back`, `push_front`.

**Comment by arximboldi** [comment]
While it makes sense theoretically, and it may provide a small performance advantage when using transients, note that in general there is some ammount when pushing elements into an immutable vector (the neighbouring elements need often to be copied), so the advantage of such methods is tiny for immutable vectors.
