### ISSUE TITLE
Cannot generate cmake project in ./build directory on windows

### ISSUE THREAD

**Issue by fedormatantsev** [arximboldi/immer#148]
There is `BUILD` file in root directory that prevents tools (e.g. cmake tools for VS Code) from creating `./build` directory on windows.
It is not a problem at all, but `.gitignore` file has `build/` entry inside it, so probably `BUILD` file should be renamed somehow.

Meanwhile, one would need to configure tooling in a special way and add additional `.gitignore` entry for build directory which is annoying.

**Comment by arximboldi** [comment]
The `BUILD` file can sadly not be renamed, because it is how Bazel expects that file to be named. The `.gitignore` file already contains an ignore rule for `build-*` so you can just create build directories with that pattern.

**Comment by yesudeep** [comment]
I think you could rename the `BUILD` file to `BUILD.bazel`. It's best practice, btw. 
On case insensitive file systems "build" would conflict with "BUILD". 

https://github.com/bazelbuild/rules_go/issues/866

**Comment by arximboldi** [comment]
Thanks @yesudeep for the tip, i'm not super familiar with Bazel. Very happy to accept that change then!
