### ISSUE TITLE
Assertion failure with immer::flex_vector_transient

### ISSUE THREAD

**Issue by ddcc** [arximboldi/immer#16]
I have a small dummy program that appends and erases unsigned integers from an `immer::flex_vector_transient`. By default, I understand that the container will use `immer::refcount_policy` (with `immer::no_transience_policy`), and everything works fine.

Since the keys are just unsigned integers (32-bits), I'd like to disable reference counting in order to measure the runtime overhead. By changing the container to use `immer::no_refcount_policy`, this automatically selects `immer:: gc_transience_policy`, which leaks memory without the Boehm GC (as stated in the documentation).

I don't care about the memory leak since this is just a test program, but I encounter an assertion failure at runtime that is unexpected:
`test: ../../immer/immer/detail/rbts/position.hpp:160: leaf_sub_pos<NodeT> immer::detail::rbts::make_leaf_sub_pos(NodeT *, immer::detail::rbts::count_t) [NodeT = immer::detail::rbts::node<unsigned int, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap, 1024>, immer::no_refcount_policy, immer::gc_transience_policy, false, false>, 5, 6>]: Assertion 'count <= branches<NodeT::bits_leaf>' failed.`

Is this supposed to occur? If I manually choose `immer::no_transience_policy`, the assertion doesn't fail. This is the test program: [test.txt](https://github.com/arximboldi/immer/files/1307906/test.txt)

**Comment by arximboldi** [comment]
Thanks a lot @ddcc, good catch!
The problem was that copying the transient was not correctly handling the tokens that are used internally to track ownership in the `gc_transience_policy`, thus the transient was updating in-place nodes that were visible via two different variables... (`v2` and `v` inside `erase`).
I already made a fix, will merge as soon as Travis gives a green light.

**Comment by ddcc** [comment]
Thanks for the quick fix!
