### ISSUE TITLE
Add watch to atoms

### ISSUE THREAD

**Issue by CurriedFloat** [arximboldi/immer#166]
Hi :)

We use `condition_variable::wait_for ` in our code.
It would be nice to be able to use immer atoms for this but if I'm not misunderstanding we would have to do some sort of busy-waiting because we cant access the internal lock.

Clojure agents/atoms/vars/refs have the add-watch function.
https://clojuredocs.org/clojure.core/add-watch

Would there be a possibility of adding this the the atoms?

**Comment by arximboldi** [comment]
Hmmm, but you want the lambda registered with `add-watch` to be called in the thread that calls `add-watch` or in the thread that changes the atom? In the latter case, it does not replace the use-case for `condition_variable::wait_for`. But in the former case, this is defo not easy in C++, and you would need to pass an executor or alike to `add-watch`.

In either case, there would be some overhead that I'm not sure is appropriate for `atom` itself.

When dealing with "observable" data, I use cursors in Lager: https://sinusoid.es/lager/cursors.html

Note, however, that there are some caveats with using Lager cursors in a multi-threaded context. If you want I'd be happy to dig deeper in your use-case (we can also open a consulting tab if this is part of a commercial project).

Cheers!

**Comment by CurriedFloat** [comment]
> Hmmm, but you want the lambda registered with `add-watch` to be called in the thread that calls `add-watch` or in the thread that changes the atom? In the latter case, it does not replace the use-case for `condition_variable::wait_for`. But in the former case, this is defo not easy in C++, and you would need to pass an executor or alike to `add-watch`.
>
Yes you're right, I would expect `add-watch` to call the lambda on the "atom changing thread" not the "waiting thread".
Guess I need something that blocks, not registers a lambda. 

> In either case, there would be some overhead that I'm not sure is appropriate for `atom` itself.
> 
Dont complect on my account :)

> When dealing with "observable" data, I use cursors in Lager: https://sinusoid.es/lager/cursors.html
> 
> Note, however, that there are some caveats with using Lager cursors in a multi-threaded context. If you want I'd be happy to dig deeper in your use-case (we can also open a consulting tab if this is part of a commercial project).
> 
> Cheers!

I have looked at Lager and Rx for observable data, I think either would do the job well, but I was hoping to be able to just use immer. I will have to look closer at lager cursors.

Thanks! :)

**Comment by arximboldi** [comment]
You're welcome! Closing this for now, let me know if I can be of further aid.
