### ISSUE TITLE
Add vector::take_last method

### ISSUE THREAD

**Issue by stefan-pdx** [arximboldi/immer#170]
Hello!

I'm curious how much effort it would take to implement a `vector::take_last(size_type elems)` method, similar to [Clojure's `take-last`](https://clojuredocs.org/clojure.core/take-last). I have a use-case where I'd like to grow a large, immutable vector but make cheap copies of the last _n_ values.

Thanks for continuing to maintain this impressive library!

**Comment by jon-smith** [comment]
If I’m understanding correctly, perhaps `flex_vector::drop` fits your requirements?

**Comment by stefan-pdx** [comment]
That works! Using `flex_vector.drop(flex_vector.size() - n)` works since `size()` is _O(1)_. Thanks for the quick response!

**Comment by arximboldi** [comment]
Thanks Jon for your quick answer!
