### ISSUE TITLE
Boost.Hana integration

### ISSUE THREAD

**Issue by Hrle97** [arximboldi/immer#174]
Did anyone try to do this? I feel like these two libraries would blend together really nicely!

**Comment by arximboldi** [comment]
What kind of integration are you thinking abou?

**Comment by Hrle97** [comment]
Just modelling Hana's concepts in terms of Immer. Vectors would make nice Sequences was my initial thought.

**Comment by arximboldi** [comment]
Immer is most valuable at runtime, Hana works more at compile-time. I provided a more detailed answer in #138. Zug on the other hand I think actually could be indeed useful to express compile-time algorithms. There is some trickyness in doing constexpr stuff with lambdas though pre C++20.
