### ISSUE TITLE
Transients fail to compile when using boxed incomplete types

### ISSUE THREAD

**Issue by jeaye** [arximboldi/immer#176]
Hello! I've read that immer doesn't handle complete types in its containers, which is why it's provided `box`. I'm using `box` successfully, with `vector`, `map`, and `set`, but I'm unable to compile the transient forms of all of them.

A full reproduction case is included; I'm using the latest immer master and compiling with GCC 10.2.0 on Arch.

```c++
#include <iostream>

#include <immer/vector.hpp>
#include <immer/box.hpp>

struct object
{
  using vector_type = immer::vector<immer::box<object>>;

  int data;
};

int main()
{
  // This works fine.
  object::vector_type v;
  v = v.push_back(object{ 1 });
  std::cout << v[0].get().data << std::endl;

  // Fails to compile. Incomplete type.
  //object::vector_type::transient_type t;
}
```

The error I see from GCC:

```
❯ c++ -I lib/immer main.cpp 
main.cpp: In function ‘int main()’:
main.cpp:20:39: error: aggregate ‘immer::vector<immer::box<object> >::transient_type t’ has incomplete type and cannot be defined
   20 |   object::vector_type::transient_type t;
      |                                       ^
```

**Comment by jon-smith** [comment]
Hi jeaye, `vector_type::transient_type` is incomplete in `vector.hpp` (uses forward declared `vector_transient`), so you just need to `#include <immer/vector_transient.hpp>`

**Comment by jeaye** [comment]
Oh no! :facepalm: I'm sorry for the inconvenience. Thank you so much for pointing this out.

**Comment by arximboldi** [comment]
Thanks @jon-smith for the quick response!
