### ISSUE TITLE
Compatibility with GCC 5/Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by ddcc** [arximboldi/immer#18]
Are you interested in patches for support with the default GCC 5.4.1 on Ubuntu 14.04? Even compiling with C++14, there are issues with some braced initializer lists and uses of `decltype(auto)`. I initially made some local changes for this, but ran into some difficulty understanding your usage of `std::get` on the result of `visit_maybe_relaxed_sub` in `rrbtree.hpp`, since `regular_sub_pos<NodeT>` and `relaxed_pos<NodeT>` appear to be different classes, and don't fit any of the default overloads for `std::tuple`, `std::variant`, `std::pair`, etc.

I also ran into similar issues with Clang 5.0, until I installed GCC 6.0 and Clang 5.0 selected the system headers bundled with GCC 6.0 by default.

**Comment by arximboldi** [comment]
I agree that Ubuntu LTS support is important!

Interesting... with Clang 5 I had no issues so far, and I believe I am using both LLVM's `libc++` and GNU's `libstdc++`, but I'd have to double check...

With GCC 5 though I recall having had issues, and that is why in Travis I only test from GCC 6 up. However, from what I remember, the issues were not trivial---it was GCC getting confused with the instantiations of position based traversals [1]. For other reasons too, I am considering simplifying (or getting rid of) the position based stuff. However I am busy now trying to make a first version of CHAMP mergeable before CppCon (while having quite some freelance work to finish on the side 😟). When looking at my schedule, I doubt I will be able to find time for that until late November.

But, if this is pressing for you I'd be happy to answer your questions/review code if you try to fix it yourself. I also need to finish the CLA for non-trivial contributions... 😄 

[1] Section 4.4. of the ICFP paper: https://public.sinusoid.es/misc/immer/immer-icfp17.pdf

**Comment by vincent-hui** [comment]
GCC 5.5 was released. can immer support GCC 5.5?

**Comment by vincent-hui** [comment]
Hi @ddcc , will you create pull requests to support GCC 5.4 ?

**Comment by ddcc** [comment]
Sorry, didn't end up using this in a project, and don't have any plans to in the near future.

**Comment by arximboldi** [comment]
@vincent-hui do you still need support for `5.5` I haven't tried that. Otherwise, that GCC is very old so I'm gonna close this for now.
