### ISSUE TITLE
Suggestion: make Immer STL-compatible

### ISSUE THREAD

**Issue by slburson** [arximboldi/immer#186]
It would be possible to give Immer an API almost completely compatible with that of the STL collections, so that with rare exceptions, STL client code could be converted to use Immer simply by changing some occurrences of `std::` to `immer::`.  This would make it easier for new Immer users to get started, and accelerate adoption of the package.  I will explain how it can be done.

(Before I proceed, a note of introduction: I am the author of [FSet](https://github.com/slburson/fset), the most widely-used functional collections package for Common Lisp; there's also a [Java implementation](https://github.com/slburson/fset-java).)

The reason it is possible to make Immer STL-compatible is that the STL types actually have functional semantics, even though they do not have a persistent implementation.  People naturally tend to think of functional semantics as requiring that the type have no mutating operations, but the correct definition is more subtle.  Consider this example:
```
    int a = 3;
    int b = a;
    a += 2;
```
Even though `int` is a functional type, it stil has mutating operations like `+=`.  _But_, the value of b, once this code is executed, is still 3: the assignment _by value_ of `a` to `b` has made a copy rather than causing `b` to alias `a`.  (I have to add the qualifier "by value" because, of course, C++ always allows you to introduce aliasing if you want, by using reference rather than value assignment.)

So I suggest the correct definition of a functional type is _one for which value assignment does not introduce aliasing_.  It is easily seen that the STL types have this property:
```
    std::vector<int> a{3};
    std::vector<int> b = a;
    a.push_back(7);
    // b is still {3}
```
Although this is obvious enough when pointed out, I suspect people don't stop to think about it, partly because it's a somewhat unusual property for a collection type to have.  It's not true for the built-in array types in C/C++ or, indeed, in any language I know of that supports low-level programming.  It's not true for the Java JCF collections:
```
    ArrayList<Integer> a = new ArrayList<>();
    a.add(3);
    ArrayList<Integer> b = a;
    a.add(7);
    // b is also now {3, 7}
```
I suspect that, prior to the emergence of the STL as the _de facto_ standard, numerous people rolled their own C++ collections libraries, most of which did not have functional semantics.  But for whatever reasons, the STL does.

Let's go back to my assertion that `+=` is a mutating operation on `int`.  You might have objected, when you read it, that that isn't how you think about it; you consider `a += 2` to be shorthand for `a = a + 2`.  Fine; but by the same token, then, we should consider `a.push_back(7)`, where `a` is an STL vector, to be _semantically_ an abbreviation for `a = a.with_back(7)` (where `with_back` is a hypothetical _functional_ update operator I just invented).  The STL implementation doesn't actually work that way, and you wouldn't want it to, because it would have to do an O(n) copy.  But Immer doesn't have this problem!  You could actually rename the existing `immer::vector::push_back` to `with_back`, and then implement `immer::vector::push_back` as `with_back` followed by assignment to `*this`.  The result would be semantically identical to `std::vector::push_back`.

The same is true for all the ostensibly mutating operations on STL collections; you could make compatible Immer versions of all of them.  To achieve (nearly) full STL compatibility you would need to build out some more classes; for example, I think you would want to rename `immer::set` and `immer::map` to `unordered_set` and `unordered_map`, and then add `set` and `map` classes that use functional binary trees, so they would be ordered, as clients of `std::set` and `std::map` will expect.  (I used functional binary trees for FSet because I wrote it back in 2005, before I had heard of Phil Bagwell's work, so I have code you can crib from if you want.)

The only place I can see where the result would not be plug-compatible with the STL would be when an allocator is being supplied in a template instantiation.  I don't know how common that is; I've never done it.  (Maybe you could even add an `Allocator` parameter to your templates in an STL-compatible way.)

The bad news, of course, is that doing all this will change the Immer API, requiring existing client code to be revised.  Well, with some effort, maybe you could make the choice of API a build-time option.  (Or, you could fork the entire library.)

But the good news will be a lowered barrier to adoption and therefore more users.

**Comment by arximboldi** [comment]
Have you checked the transients API in Immer?

https://sinusoid.es/immer/transients.html

Note that actually transients in Immer are basically as usable as the immutable data-structures, they simply provide an alternative API. In a later version I consider merging the two, in ways like you suggest. I still have to decide when and how.

Thank you for your thoughtful discussion of the issue!
