### ISSUE TITLE
Documentation site has expired certificate

### ISSUE THREAD

**Issue by esp1** [arximboldi/immer#195]
The immer documentation site https://sinusoid.es/immer/#contents has an invalid SSL certificate. It looks like it is based on a root certificate that expired on Sept 30, 2021:
![image](https://user-images.githubusercontent.com/73882/141188864-fdbfd7d9-6740-489b-a207-2179291f96f4.png)

**Comment by CapSel** [comment]
Are you sure you have newest certificate pack? X3 is expired but R3 is also signed by X1, that should be in your CA certificate pack.

**Comment by esp1** [comment]
I tried this out on the latest version of various desktop (MacOS 11.6 - Safari, Chrome, Brave) and mobile (iOS 15.1 - Safari, Chrome, Firefox, Firefox Focus) browsers, and this certificate error shows up on all of them. The only browser I found it does work on is the latest version of Mac desktop Firefox (version 94.0.1 (64-bit)).

**Comment by CapSel** [comment]
I reproduced this problem with iOS device and epiphany (gnome web) on Linux. Firefox and Brave are not affected on Linux.
I think solution would be to add X1 into certificate chain on server.

**Comment by arximboldi** [comment]
Hi, thank you all for debugging this. It was reported by someone else some time ago and I could also not reproduce it. The certificate is Let's encrypt auto-generated. I'm not sure how to fix it. Anyway I would like to migrate that server at some point from the Debian into NixOS, which is much easier to manage. Hopefully that will fix the issue. It may still take a few days or weeks until I find time to do that though.

**Comment by esp1** [comment]
Closing this issue as the doc site works fine for me now
