### ISSUE TITLE
Add maps with keys extracted from the value

### ISSUE THREAD

**Issue by arximboldi** [arximboldi/immer#198]
Solves the issue of:
```c++
struct something {
  id_t id;
   ...
};

using something_map = immer::map<id_t, something>;
```

**Comment by arximboldi** [comment]
With this new type one could do something like:
```c++
struct something {
  std::string id;
   ...
};

auto x = immer::object_map<something>{}
   .insert(something{"foo", ...})
   .insert(something{"bar", ...}));

static_assert(std::is_same_v<decltype(x)::key_type, std::string>);
assert(x.find("foo") != nullptr);
assert(x.at("foo") == something{"foo", ...});
assert(x.count("foo") == 1);
```
We could say that by default it access the `id` or `key` attribute, but an arbitrary key projection could be used by using customization points:
```c++
struct something {
  int name;
  ...
};

struct something_key {
   int operator()(const something_key& x) { return x.name; }
};

using something_map = immer::object_map<something, something_key>{};
```
Not sure if `object_map` is the best name for this construction. Happy to hear other ideas!

**Comment by deadb0d4** [comment]
Cool, let me try it. It indeed seems like a good first issue here :)

**Comment by deadb0d4** [comment]
I skimmed through the `{map,set}.hpp`, I think about the following (don't mind my code style, I will adjust it when I am working on the PR):

```c++

struct DefaultIndexer {
  template <class T>
  auto operator() (const T& t) {
    return t.id;
  }
};

// it will be a bit tedious to define concept for Indexer w/o c++20
template <typename T, typename Indexer = DefaultIndexer>
class single_hash_index {
 private:
  using key_type = decltype(Indexer()(T()));

 public:
  // semantics of the immer::map

 private:
  immer::set<T> values;
};
```
The idea is that user can specialize `DefaultIndexer::operator()` as well as providing its own `Indexer`. @arximboldi do you see any issues with this? I would like to have someone's approve before working on PR...

**Comment by arximboldi** [comment]
Yes, the idea is to provide a new type with an interface very similar to `immer::map`, and also based on `detail::champ` as implementation. You can achieve the right interface by customizing `project_value` and the other callbacks that are used with `champ`. It should be not too difficult if you are already familiar with templates and the Immer interface.

**Comment by arximboldi** [comment]
Btw @deadb0d4, are you on Twitter? I'm gonna make an announcement about the new type, and I would be very happy to credit you with a direct mention!

**Comment by deadb0d4** [comment]
@arximboldi Thank you very much for your help. It's been a pleasure working on this. No, I am not :) Feel free to just mention the issue or/and my nickname on GitHub :D
