### ISSUE TITLE
vector::iterator + X expects X to be int, not size_type

### ISSUE THREAD

**Issue by jsyjr** [arximboldi/immer#232]
I have not investigated other iterators nor other containers but would expect the issue to be relatively widespread.

**Comment by arximboldi** [comment]
Is it `int` or `std::ptrdiff_t` (aka `iterator_traits::difference_type`)? Note that `size_type` is unsigned so it is actually unsuitable for `operator+`.

**Comment by jsyjr** [comment]
Learn something new everyday.  Thanks for the quick reply.

**Comment by arximboldi** [comment]
Glad it helped!
