### ISSUE TITLE
Create a new release of this library

### ISSUE THREAD

**Issue by maierlars** [arximboldi/immer#237]
Hello @arximboldi ,
the latest released version is 0.7.0, which was released Nov 2021. I assume a few bug fixes happened since then and I would be really glad if you could create a new release. A minor release is fine, like 0.7.1? 

Or maybe there is already something planned. If so, what is the ETA?

Thank you so much for this awesome library.

**Comment by arximboldi** [comment]
Actually there has been some nice new features in between, specifically map/set transients! I'll make a release soon.

**Comment by arximboldi** [comment]
https://github.com/arximboldi/immer/releases/tag/v0.8.0

**Comment by maierlars** [comment]
Thank you so much! 👍🏽
