### ISSUE TITLE
Implementation into a hosted language

### ISSUE THREAD

**Issue by ShalokShalom** [arximboldi/immer#242]
Hi there :)

Let me ask a probably out-of-place question: 
Can I use this library, to implement immutable data structures to a language, that is implemented in C++?

I am specifically thinking about GDScript 
https://github.com/godotengine/godot/blob/master/modules/gdscript/
As you can see, it is integrated as VM and as a module. Thanks a lot

**Comment by arximboldi** [comment]
Making it easy or at least feasible to integrate in language implementations is one of the goals of the library. The codebase contains examples of Scheme and Python bindings. @jeaye has also integrating it in [jank](https://github.com/jank-lang/jank). Lemme know if you have any issues with it :smile:

**Comment by arximboldi** [comment]
Also: exciting to see support into Godot, which is an amazing product! Are you aiming for it to be provided in the langauge by default, or as an external library?

**Comment by ShalokShalom** [comment]
Ok, I am new to C++ and programming in general. I will do my best.

I doubt it would be accepted in GDScript
So I aim to make it part of a fork, together with some other changes.

The new language will be called Godette ;)

**Comment by arximboldi** [comment]
Great. Good luck!

**Comment by ShalokShalom** [comment]
I feel like, this is WAY over my head 😅
