### ISSUE TITLE
Logo is hidden when using GitHub dark theme

### ISSUE THREAD

**Issue by tocic** [arximboldi/immer#254]
The logo is partially hidden when you look at it using the default dark theme.

"Dark default" vs "Light default" for the `README`:

![image](https://user-images.githubusercontent.com/22129543/230119963-b4caa68a-4cf4-40d5-9a3c-1c41a4f4fa81.png)

![image](https://user-images.githubusercontent.com/22129543/230120408-880a8bbc-0606-4bed-9f24-8a9f4c37997d.png)

Consider changing the background to white.

**Comment by arximboldi** [comment]
good catch!
