### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by altschuler** [arximboldi/immer#273]
It'd be great with a new tagged release. Seems like there has been substantial work done (personally I'm eager to use the c++20 range fixes) since v0.8.0, and vcpkg needs a new tag to be able to update the package (per https://github.com/microsoft/vcpkg/pull/34216).

Sorry that I didn't realize there is actually a history of version tags for immer, I just noticed the single GH release from last year.

Thank you! :)

**Comment by arximboldi** [comment]
https://github.com/arximboldi/immer/releases/tag/v0.8.1

Thanks!
