### ISSUE TITLE
C++17 [[nodiscard]]

### ISSUE THREAD

**Issue by Toby-Scantlebury** [arximboldi/immer#29]
Motivation:
It is very easy for most C++ developers to write `vec.push_back();` instead of `vec = vec.push_back();`. Currently no warnings are generated for this error.

Solution:
Almost all functions should be annotated with [[nodiscard]] on compilers which support it.

Notes: 
1. If detecting supported compilers is a problem then a macro which can be defined in the build process is a potential workaround.
2. Due to a bug with `warn_unused_result` detailed [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38172) (and still not fixed), using GNU extensions isn't a good path.

**Comment by arximboldi** [comment]
Very good point.  Will fix!

Toby-Scantlebury <notifications@github.com> writes:

> Motivation:
> It is very easy for most C++ developers to write `vec.push_back();` instead of `vec = vec.push_back();`. Currently no warnings are generated for this error.
>
> Solution:
> Almost all functions should be annotated with [[nodiscard]] on compilers which support it.
>
> Notes: 
> 1. If detecting supported compilers is a problem then a macro which can be defined in the build process is a potential workaround.
> 2. Due to a bug with `warn_unused_result` detailed [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=38172) (and still not fixed), using GNU extensions isn't a good path.
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/arximboldi/immer/issues/29

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by arximboldi** [comment]
Addressed :)
