### ISSUE TITLE
immer::vector<int> constructor fails to compile

### ISSUE THREAD

**Issue by Toby-Scantlebury** [arximboldi/immer#30]
The constructor `immer::vector<int> aa(1,2);` fails to compile whereas `immer::vector<int> aa(1,2.0);` is fine. It appears that the wrong constructor is being deduced in the first instance.

This is with `gcc version 7.2.0 (Ubuntu 7.2.0-1ubuntu1~16.04)` which reports the following error:

```
In file included from lib/immer/vector.hpp:23:0,
                 from test.cpp:1:
lib/immer/detail/rbts/rbtree.hpp: In instantiation of ‘static auto immer::detail::rbts::rbtree<T, MemoryPolicy, B, BL>::from_range(Iter, Iter) [with Iter = int; T = int; MemoryPolicy = immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>; unsigned int B = 5; unsigned int BL = 6]’:
lib/immer/vector.hpp:130:35:   required from ‘immer::vector<T, MemoryPolicy, B, BL>::vector(Iter, Iter) [with Iter = int; T = int; MemoryPolicy = immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>; unsigned int B = 5; unsigned int BL = 6]’
test.cpp:5:26:   required from here
lib/immer/detail/rbts/rbtree.hpp:68:37: error: invalid type argument of unary ‘*’ (have ‘int’)
             result.push_back_mut(e, *first);
```

**Comment by arximboldi** [comment]
Similar problems arise with `std::vector` due to ambiguities in C++'s type
system.  As a workaround, you should be able to dysambiguate using:

    immer::vector<int> aa{{1,2}};

Does that work for you?

Toby-Scantlebury <notifications@github.com> writes:

> The constructor `immer::vector<int> aa(1,2);` fails to compile whereas `immer::vector<int> aa(1,2.0);` is fine. It appears that the wrong constructor is being deduced in the first instance.
>
> This is with `gcc version 7.2.0 (Ubuntu 7.2.0-1ubuntu1~16.04)` which reports the following error:
>
> ```
> In file included from lib/immer/vector.hpp:23:0,
>                  from test.cpp:1:
> lib/immer/detail/rbts/rbtree.hpp: In instantiation of ‘static auto immer::detail::rbts::rbtree<T, MemoryPolicy, B, BL>::from_range(Iter, Iter) [with Iter = int; T = int; MemoryPolicy = immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>; unsigned int B = 5; unsigned int BL = 6]’:
> lib/immer/vector.hpp:130:35:   required from ‘immer::vector<T, MemoryPolicy, B, BL>::vector(Iter, Iter) [with Iter = int; T = int; MemoryPolicy = immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>; unsigned int B = 5; unsigned int BL = 6]’
> test.cpp:5:26:   required from here
> lib/immer/detail/rbts/rbtree.hpp:68:37: error: invalid type argument of unary ‘*’ (have ‘int’)
>              result.push_back_mut(e, *first);
> ```
>
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/arximboldi/immer/issues/30

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by Toby-Scantlebury** [comment]
Thanks for your prompt response.

I believe your suggestion calls the list initializer constructor instead of the `vector(size_type n, T v = {})` constructor.

This is not a problem for me now (after the initial confusion when first using the library) but I think it's worth fixing so others can avoid the papercut.

`std::vector` does not have this problem (I checked), maybe because they take a reference to `T` rather than by value (which is probably a good idea). Or possibly some other magic.

As I'm no longer affected please feel free to close the issue if you do not wish to change the behaviour. I'll let you know if I encounter any other problems using your wonderful library.

**Comment by arximboldi** [comment]
Oh, ok, thanks for the further clarification!

I'll leave the issue open for now because I agree that this is
surprising behavior.

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by vincent-hui** [comment]
Hi, did anyone tried Clang in Visual Studio 2017?? https://blogs.msdn.microsoft.com/vcblog/2017/03/07/use-any-c-compiler-with-visual-studio/

**Comment by Toby-Scantlebury** [comment]
#31 solves this issue

**Comment by arximboldi** [comment]
Thanks for checking Toby!
