### ISSUE TITLE
Feature Request: Vector constructor from iterator and sentinel

### ISSUE THREAD

**Issue by apmccartney** [arximboldi/immer#31]
Firstly, thank you for authoring this library. It's a wonderful contribution to the C++ open source community.

I would propose an additional constructor for `immer::vector` from an **_iterator_** and **_sentinel_**, similar to the existing constructor accepting two iterators. Here, by _**sentinel**_, I mean value of a type equality comparable to an instance of the **_iterator_** type.

My motivation for this request is to improve interoperability with the lazy ranges provided by the [range v3](https://github.com/ericniebler/range-v3) library. In many of these types, the `begin` and `end` methods return values of distinct types. Eric Niebler provides some justification for this peculiarity on his blog [here](http://ericniebler.com/2014/02/21/introducing-iterables/).

**Comment by arximboldi** [comment]
Thanks for the request. I think this is a very sensible request and it should be implemented. We shall me aware of potential ambiguities though, see #30

**Comment by apmccartney** [comment]
If pull requests are welcome, I think I can provide an implementation (along with corresponding tests), with sufficient specificity.

**Comment by arximboldi** [comment]
Austin McCartney <notifications@github.com> writes:

> If pull requests are welcome, I think I can provide an implementation
> (along with corresponding tests), with sufficient specificity.

Of course!

Thanks a lot :)

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by arximboldi** [comment]
Thank you very much @apmccartney for addressing this issue!
