### ISSUE TITLE
Problem using immer::vector<A> inside class A

### ISSUE THREAD

**Issue by DeifLou** [arximboldi/immer#36]
Hi. I ran into a problem when trying to pass a `immer::vector<A>` as an argument to a constructor of `A`. The minimal code that reproduces the problem is this:
``` cpp
#define USE_IMMER_VECTOR

#ifdef USE_IMMER_VECTOR

#include <immer/vector.hpp>
template <typename T>
using Vector = immer::vector<T>;

#else

#include <vector>
template <typename T>
using Vector = std::vector<T>;

#endif

struct A
{
    A(Vector<A> const &) {}
};

int main()
{
    return 0;
}
```
If the line `#define USE_IMMER_VECTOR` is commented then `std::vector`is used and everything works fine but, if it is not commented, then `immer::vector` is used and I get 5 errors that seem related compiling with gcc 6.3.0:
```
..\..\..\install\release\shared\include/immer/detail/rbts/node.hpp:942:40: error: invalid application of 'sizeof' to incomplete type 'A'
     constexpr auto sizeof_elem = sizeof(T);

..\..\..\install\release\shared\include/immer/detail/util.hpp:35:41: error: invalid application of 'sizeof' to incomplete type 'A'
     typename std::aligned_storage<sizeof(T), alignof(T)>::type;

..\..\..\install\release\shared\include/immer/detail/rbts/node.hpp:124:51: error: 'struct immer::detail::rbts::node<A, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5u, 5u>::leaf_t' has no member named 'buffer'
         return immer_offsetof(impl_t, d.data.leaf.buffer)

..\..\..\install\release\shared\include/immer/detail/rbts/node.hpp:125:23: error: 'buffer' is not a member of 'immer::detail::rbts::node<A, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5u, 5u>::leaf_t'
             +  sizeof(leaf_t::buffer) * count;

..\..\..\install\release\shared\include/immer/detail/rbts/node.hpp:943:85: error: constexpr call flows off the end of the function
     constexpr auto space = node_t::max_sizeof_inner - node_t::sizeof_packed_leaf_n(0);
```
I don't really know if there is something wrong with immer or if I should be doing things differently.
Thanks.

**Comment by apmccartney** [comment]
Instantiating `std::vector` or any other STL container with an incomplete type is undefined behavior until the C++17 standard, where specific exemptions were made.

From the C++11 standard:
> 17.6.4.8 Other functions (...) 2. the effects are undefined in the following cases: (...) In particular - if an incomplete type (3.9) is used as a template argument when instantiating a template component, unless specifically allowed for that component

See this [thread](https://stackoverflow.com/questions/18672135/why-c-containers-dont-allow-incomplete-types) for more information.

**Comment by DeifLou** [comment]
Ok, I see, thank you for the clarification.
In the thread it's said that the limitation could be avoided and that there exist boost containers that are allowed to be instantiated with incomplete types. I leave that as a suggestion (I'm not really well versed in c++ and don't know if could be any bad implications).
A recursive data structure like it's commented in that thread is what I'm after, a xml like immutable tree.

**Comment by arximboldi** [comment]
@DeifLou this is a known limitation and I already had an issue about this: https://github.com/arximboldi/immer/issues/24
My plan is to add quite soon support for incomplete types in `immer::box`. In this way, you shall be able to solve the problem by just doing `immer::vector<immer::box<T>>`.

The reason vectors at the moment require complete types is because part of the shape of the internal data structure depends on the size the stored elements themselves, as to optimize the cache utilization. You can learn more about that in the talks and paper that I link in the README.

Cheers!

**Comment by arximboldi** [comment]
@DeifLou I have just tested that using `immer::vector<immer::box<A>>` works. I am adding test coverage for this use-case to the codebase.

**Comment by DeifLou** [comment]
Hi. Thanks for your time.
As I said I'm trying to implement a xml like tree (with immer::map for attributes and immer::flex_vector for the children). I'm using std::shared_pointer for the nodes instead of immer::box for two reasons:
1. I have to return a nullptr for some operations like 'child_with_tag(...)' that returns nullptr if there are no child nodes with that tag.
2. I want to know if two boxes/pointers point to the same underlying object.

In the first case I could use an std::optional, there is no problem with that.
In the second case I just want to know if two boxes point to the same underlying object with a shallow comparison, but I see that the code performs a deep comparison if they don't. The same is true with map and flex_vector. But maybe I have to rethink the way I do things and it's not really necessary to know if the underlying objects are the same... I'll check.

Thanks for everything.

**Comment by arximboldi** [comment]
> In the first case I could use an std::optional, there is no problem with that.

That is correct.

> In the second case I just want to know if two boxes point to the same underlying object with a shallow comparison, but I see that the code performs a deep comparison if they don't. The same is true with map and flex_vector.

The boxes just point to the same object if they come from the same place. However, in case the pointers are different, they could still hold the same _value_, even if the objects where created in different moments, thus the need for a deep comparison. If all your value trees are derived from the same place, comparing them will be proportional to the amount of differences between them, which should be fine.

**Comment by DeifLou** [comment]
Well, I use a box now and everything seems fine.
But I was thinking possible future scenarios and came with this: imagine I want to check if the tree has cycles, if some ancestor node of node A is also its descendant. I think I would need some kind of shallow comparison. Any thoughts/advice?

**Comment by arximboldi** [comment]
If it is a tree it doesn't have cycles. You should not be able to build a structure with cycles using Immer's immutable API.
