### ISSUE TITLE
does this integrate with the RangeV3 library?

### ISSUE THREAD

**Issue by BrannonKing** [arximboldi/immer#38]
How does this library integrate with the RangeV3 library? Is there overlap in functionality? Can the collections here be used as backing storage for the RangeV3 iterators?

**Comment by BrannonKing** [comment]
After reading a little more about it, what I really want to know is what RangeV3 traits the collections in immer provide. I want to be able to pass immer's vector or array or flex_vector into a method (and maybe an STL vector too). I see that the RangeV3 library does some fancy constraints on templated method parameters. I want to understand how to repeat that.

**Comment by arximboldi** [comment]
Immer collections are normal iterable collections so they can function with a range-v3. Although, one notable particularity of Range V3 is that it introduces the notion of iterator sentinels to be able to mark the end of a collection with a different type than the normal running iterator. There is an ongoing effort to make Immer collections to be constructed from such special ranges: https://github.com/arximboldi/immer/pull/32 You can see an example of the level of integration achieved here: https://github.com/apmccartney/immer-range-v3-integration/blob/master/main.cpp
