### ISSUE TITLE
extras not compatible with GCC 6.4

### ISSUE THREAD

**Issue by BrannonKing** [arximboldi/immer#39]
When compiling with GCC 6.4, I get this error:
g++.exe: error: unrecognized command line option '-fsanitize-coverage=trace-pc-guard'; did you mean '-fsanitize-coverage=trace-pc'?

It comes from the CMakeLists.txt in the extras folder. Can we not make the extras use the ENABLE_SANITIZER option from the parent? Is trace-pc-guard a Clang-only thing?

**Comment by arximboldi** [comment]
`ENABLE_SANITIZER` is just used to enable sanitizers on CI, using Clang, and is not guaranteed to work for any particular purpose. If you wanna enable any particular sanitizer on Gcc you are gonna have to play with the CXXFLAGS and LDFLAGS yourself.

**Comment by arximboldi** [comment]
Ohhh! I see, yeah the fuzzers use `libFuzzer` and the current settings
to compile them only work with Clang (I am not even sure it is possible
to use it with GCC at all).  I will look into the options set, thanks!

Brannon King <notifications@github.com> writes:

> I don't want to enable any sanitizers. The point is that it is always enabled in `extra/fuzzers/CMakeLists.txt` with no regard to the compiler in use nor any other flags.
>
> -- 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/arximboldi/immer/issues/39#issuecomment-381410231

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by BrannonKing** [comment]
I also see this error: clang++.exe: error: unsupported option '-fsanitize=address' for target 'x86_64-w64-windows-gnu'

**Comment by arximboldi** [comment]
I see. For now, all I can recomend is to just avoid building the extras, since that is mostly experimental code.
