### ISSUE TITLE
License Change?

### ISSUE THREAD

**Issue by adishavit** [arximboldi/immer#4]
I read [on reddit](https://www.reddit.com/r/cpp/comments/5f5z0p/immer_library_of_persistent_and_immutable_data/dahskkf/) that you are planning a license change to a more liberal license.  
When is that expected and what license might that be?

**Comment by arximboldi** [comment]
There is probably a license change coming before the 1.0 release (around Q2 2017). Probably LGPL, but it's not 100% decided. If that does not suit your needs, I am happy to negotiate individual license grants.

**Comment by adishavit** [comment]
I have no particular license needs just now, it's just that the amount of eyeballs looking at your code, finding bugs, making fixes and PRs, might be significantly lower with GPL. 

On a different note, I wonder how LGPL fits with header only templates?
It is usually suitable for creating decoupled DLLs or server services. It is unclear how it applies if the code is directly "pasted" into the users code as with `#include`ed files.

**Comment by arximboldi** [comment]
The LGPL explicitly states that stuff that lives in a header (like templates) is ok if it is not dynamically exchangeable. You can use whatever license you want for your application that uses the library. However, if you modify the library itself, you have to give a copy of your changes to the library licensed under the LGPL to whoever you are giving binaries derived from it. It is probably a good compromise between the library being usable in proprietary applications and avoiding people not contributing back.

**Comment by arximboldi** [comment]
FYI, the license has been changed to LGPLv3+
