### ISSUE TITLE
operator==() may return bad result

### ISSUE THREAD

**Issue by Guiguiprim** [arximboldi/immer#46]
Hi !

First off, thanks for this library !

While trying to build my first application with it, I found a pretty sad bug:

In my code, I have a data of type immer::vector<immer::flex_vector<bool>>.
After applying a transformation to this data, when checking if something did actually changed, the operator equal regularly return true when it should return false.

The following code will assert (on linux mint 64bit build with clang 3.8.1).
```c++
    using bool_vec = immer::flex_vector<bool>;
    immer::vector<bool_vec> v0;
    auto tv = v0.transient();
    tv.push_back(bool_vec(9, false));
    tv.push_back(bool_vec(10, false));
    tv.push_back(bool_vec(8, false));
    tv.push_back(bool_vec(6, false));
    tv.push_back(bool_vec(9, false));
    tv.push_back(bool_vec(7, false));
    tv.push_back(bool_vec(8, false));
    tv.push_back(bool_vec(9, false));
    tv.push_back(bool_vec(10, false));
    v0 = tv.persistent();

    auto v1 = v0.update(1, [](bool_vec vec) { return vec.set(8, true); });

    assert(!(v == v1));
```

**Comment by arximboldi** [comment]
I guess the assertion you want is `v0 != v1`, correct? There is no variable named `v`.

**Comment by Guiguiprim** [comment]
Yes my bad, `assert(!(v0 == v1));` obviously.

**Comment by arximboldi** [comment]
A fix is on the way. Thanks again for reporting this!

To ensure responsive support in the future, if you are using Immer in a commercial project, please consider sponsoring the project (via [Patreon](https://www.patreon.com/sinusoidal) or just drop me an email for other agreements :smile: )
