### ISSUE TITLE
compilation error with Clang 5.0.1 on Windows

### ISSUE THREAD

**Issue by BrannonKing** [arximboldi/immer#54]
When compiling with Clang 5.0.1 on Windows I get this error:

```
In file included from C:/Workspace/ceg/cmake-build-debug/immer-src\immer/flex_vector.hpp:25:
In file included from C:/Workspace/ceg/cmake-build-debug/immer-src\immer/memory_policy.hpp:24:
In file included from C:/Workspace/ceg/cmake-build-debug/immer-src\immer/heap/heap_policy.hpp:26:
C:/Workspace/ceg/cmake-build-debug/immer-src\immer/heap/thread_local_free_list_heap.hpp:44:39: error: cannot compile this non-trivial TLS destruction yet
thread_local_free_list_storage<Heap>::head {nullptr, 0};
```

I do not see any errors with GCC 7.3

**Comment by arximboldi** [comment]
It seems like Clang on Windows does not support thread-local objects with destructors. You can still use `immer` by disabling the `thread_local_Free_list_heap` from the memory policy. You can do so by passing a different memory policy as described in https://sinusoid.es/immer/memory.html, or simply by passing defining by passing `-DIMMER_NO_FREE_LIST=1` to the compiler (this is, enabling such preprocessor definition at build-system level). I hope this helps!
