### ISSUE TITLE
Map with B>5 will not work (silently)

### ISSUE THREAD

**Issue by fedormatantsev** [arximboldi/immer#63]
Firstly, thanks for publishing Immer. It's very useful and it's a great source of inspiration at the same time.

I was playing around with my own implementation of CHAMP map and faced with a popcount problem: gcc's popcount is for 32 ints (it just ignores extra bits), but I used 6 branches per node, hence the fix for me was to use `__builtin_popcountll()`
instead.
I looked through immer's map implementation and didn't find any checks for `B`. I had no time to actually check it, but it looks like the map is broken for `B = 6` and it will consider a lot of data as collision so performance is lost silently.

If you consider this as a bug, we could collaborate further on that.

**Comment by arximboldi** [comment]
Yeah, also you can see in `immer/detail/hamts/bits.hpp` that the bitmap is hardcoded to `std::uint32_t`. The right solution would be to make `bitmap_t` dependent on `B` and the overload `count_t popcount(bitmap_t)` to use the right overload depending on B. I'd be happy to review your code and guide you if you want to do the change yourself. The change is actually not that big at all.

And thanks for the kind words, that's encouraging!

**Comment by fedormatantsev** [comment]
I'll hang with it this weekend. Looks pretty simple but who knows :)

**Comment by fedormatantsev** [comment]
#65

**Comment by arximboldi** [comment]
Thanks a lot for fixing this and taking the time to polish the solution :smile:
