### ISSUE TITLE
Immer releases

### ISSUE THREAD

**Issue by slepasteur** [arximboldi/immer#64]
Hi,

I am trying to create a conan package for immer and have a problem with the releases of the library. The conan package must reference a release version. However, there is at the moment no tag on the repository identifying the different releases of the library. Would it be feasible to create such tags?

Thanks.

**Comment by arximboldi** [comment]
Awesome! In which Conan repository are you planing to add the library?

And yeah, I haven't been defining numbered releases and been relying on commit hashes for that. I think it makes sense though. I was hoping I could finish the `set/map_transient` before 1.0, but maybe we could start soon. The library is fairly stable and it is being used already in a few projects commercial and otherwise.

**Comment by slepasteur** [comment]
Right now I added it in my repository: https://bintray.com/slepasteur/public-conan/immer%3Aslepasteur

But my goal is to submit it to bincrafters so it can be available directly on conan center. However, having a tag to refer to for the 0.4.0 version (instead of a commit hash) would be nice.

**Comment by slepasteur** [comment]
You can find the github repo for the conan recipe here: https://github.com/slepasteur/conan-immer

**Comment by arximboldi** [comment]
Yeah also the current number 0.4.0 in CMake is not really meaningful... I
will clean that up and add a tag over the weekend.

Cheers!

  JP

Simon Lepasteur <notifications@github.com> writes:

> Right now I added it in my repository: https://bintray.com/slepasteur/public-conan/immer%3Aslepasteur
>
> But my goal is to submit it to bincrafters so it can be available directly on conan center. However, having a tag to refer to for the 0.4.0 version (instead of a commit hash) would be nice.
>
> -- 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/arximboldi/immer/issues/64#issuecomment-441023169

-- 
∿∿∿  https://sinusoid.al
∿∿∿  https://sinusoid.es

**Comment by slepasteur** [comment]
Nice, thanks.

**Comment by arximboldi** [comment]
Hi @slepasteur, sorry for the late response. I just bumped the version and added a GitHub release.

If you are using Immer for a commercial project, please consider sponsoring it to ensure its long-term maintenance and support new research and development to reify our vision of simpler, more declarative, interactive software in C++. Contact: https://sinusoid.al

**Comment by arximboldi** [comment]
https://github.com/arximboldi/immer/releases/tag/v0.5.0
