### ISSUE TITLE
Restrictive licensing

### ISSUE THREAD

**Issue by darkf** [arximboldi/immer#8]
Nobody can actually use this in non-GPL-compatible codebases, and it makes no sense for a library to be GPL'd.

**Comment by ldionne** [comment]
From the README:

> Should your organization be interested in supporting it, contact: raskolnikov@gnu.org

This, along with the chosen license, suggests that the author may want to be remunerated for commercial uses of the library. This seems reasonable; do YOU work for free?

**Comment by darkf** [comment]
@ldionne Yes, I don't expect to be paid for every single thing I write, that would be unreasonable. Indeed the majority of libraries like this are actually free to use in most projects.

@arximboldi Thank you, that answers it. Hopefully you'll get picked up by someone willing to sponsor it.

**Comment by arximboldi** [comment]
FYI, the license has been changed to LGPLv3+
