### ISSUE TITLE
Two dimensions vector

### ISSUE THREAD

**Issue by arcanis** [arximboldi/immer#9]
I tried to instanciate a two-dimensions vector (`immer::vector<immer::vector<int>>`), but got the following error:

```
3rdparty/immer/includes/immer/vector.hpp:83:37: error: non-type template argument is not a constant expression
          detail::rbts::bits_t BL = detail::rbts::derive_bits_leaf<T, MemoryPolicy, B>>
```

Have you considered supporting nested structures?

**Comment by arximboldi** [comment]
Hi Mäel!

Recursive structures are meant to work, here is an example that uses them [1].

Can you let me know which compiler/system are you using (including version, e.g. output with `--version`)?

Thanks a lot!

[1] https://github.com/arximboldi/ewig/blob/master/src/ewig/buffer.hpp#L34

**Comment by arcanis** [comment]
Hmm I was on Clang 3.6 on LXSS; I'll try on 3.8, since it seems that's what you're using.

**Comment by arximboldi** [comment]
Cool! Let me know if you have any further issues.

**Comment by arcanis** [comment]
I'll close this issue, using Clang 3.8 solved this particular problem 👍
