### ISSUE TITLE
compile error with GCC 9.1.0 

### ISSUE THREAD

**Issue by Ebiroll** [arximboldi/immer#91]
When compiling immer/example/vector/vector.cpp
gcc vector.cpp

In file included from /usr/local/include/immer/detail/rbts/rbtree.hpp:11,
                 from /usr/local/include/immer/vector.hpp:11,
                 from vector.cpp:9:
/usr/local/include/immer/detail/rbts/node.hpp: In instantiation of 'constexpr const size_t immer::detail::rbts::node<int,immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5, 5>::max_sizeof_inner':
/usr/local/include/immer/detail/rbts/node.hpp:159:11:   required from 'struct immer::detail::rbts::node<int,immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5, 5>'
/usr/local/include/immer/detail/rbts/node.hpp:931:53:   required from 'constexpr immer::detail::rbts::bits_t immer::detail::rbts::derive_bits_leaf_aux() [with T = int; MP = immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>; unsigned int B = 5; immer::detail::rbts::bits_t = unsigned int]'
/usr/local/include/immer/detail/rbts/node.hpp:938:67:   required from 'constexpr const bits_t immer::detail::rbts::derive_bits_leaf<int, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5>'
/usr/local/include/immer/vector.hpp:73:51:   required from here
/usr/local/include/immer/detail/rbts/node.hpp:139:30:   in 'constexpr' expansion of 'immer::detail::rbts::node<int,immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5, 5>::sizeof_packed_inner_n(((unsigned int)immer::detail::rbts::branches<5>))'
/usr/local/include/immer/detail/rbts/node.hpp:138:34: error: dereferencing a null pointer in '*0'
  138 |     constexpr static std::size_t max_sizeof_inner =
      |                                  ^~~~~~~~~~~~~~~~
/usr/local/include/immer/detail/rbts/node.hpp: In instantiation of 'constexpr const bits_t immer::detail::rbts::derive_bits_leaf<int, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5>':
/usr/local/include/immer/vector.hpp:73:51:   required from here
/usr/local/include/immer/detail/rbts/node.hpp:938:67:   in 'constexpr' expansion of 'immer::detail::rbts::derive_bits_leaf_aux<int, immer::memory_policy<immer::free_list_heap_policy<immer::cpp_heap>, immer::refcount_policy>, 5>()'
/usr/local/include/immer/detail/rbts/node.hpp:938:18: error: 'constexpr' call flows off the end of the function
  938 | constexpr bits_t derive_bits_leaf = derive_bits_leaf_aux<T, MP, B>();
      |                  ^~~~~~~~~~~~~~~~

**Comment by Ebiroll** [comment]
To clarify,
 constexpr static std::size_t max_sizeof_leaf  = sizeof_packed_leaf_n(branches<BL>);
Expands to an error: dereferencing a null pointer in '*0'
As well as,
 constexpr static std::size_t max_sizeof_inner =  sizeof_packed_inner_n(branches<B>);

Is there anyway to rewrite sizeof_packed_leaf_n() and sizeof_packed_inner_n() or is this a gcc bug?

**Comment by arximboldi** [comment]
Hi!

I found the issue and fixed it, a PR is on the way. I just found another issue which seems indeed to be a compiler problem:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91095

I'm probably gonna add a workaround.

**Comment by arximboldi** [comment]
Merged.

**Comment by Ebiroll** [comment]
Thanks. Changes seems to work well.
Friday && Happy !
